{"attributes": {"fullName": "qx.core.AssertionError", "packageName": "qx.core", "type": "bootstrap", "name": "AssertionError", "superClass": "qx.type.BaseError"}, "type": "class", "children": [{"attributes": {"text": "<p>Assertion errors are thrown if an assertion in {@link qx.core.Assert}\nfails.</p>"}, "type": "desc"}, {"attributes": {}, "type": "constructor", "children": [{"attributes": {"line": 40, "isCtor": true, "overriddenFrom": "qx.type.BaseError", "name": "ctor"}, "type": "method", "children": [{"attributes": {}, "type": "params", "children": [{"attributes": {"name": "comment"}, "type": "param", "children": [{"attributes": {"text": "<p>Comment passed to the assertion call</p>"}, "type": "desc"}, {"attributes": {}, "type": "types", "children": [{"attributes": {"type": "String"}, "type": "entry"}]}]}, {"attributes": {"name": "failMessage"}, "type": "param", "children": [{"attributes": {"text": "<p>Fail message provided by the assertion</p>"}, "type": "desc"}, {"attributes": {}, "type": "types", "children": [{"attributes": {"type": "String"}, "type": "entry"}]}]}]}, {"attributes": {"text": ""}, "type": "desc"}]}]}, {"attributes": {}, "type": "methods", "children": [{"attributes": {"line": 64, "name": "getStackTrace"}, "type": "method", "children": [{"attributes": {"text": "<p>Stack trace of the error</p>"}, "type": "desc"}, {"attributes": {}, "type": "return", "children": [{"attributes": {"text": "<p>The stack trace of the location the exception was thrown</p>"}, "type": "desc"}, {"attributes": {}, "type": "types", "children": [{"attributes": {"type": "String", "dimensions": 1}, "type": "entry"}]}]}]}]}]}