{
  "className": "qx.core.GlobalError",
  "packageName": "qx.core",
  "name": "GlobalError",
  "superClass": "Error",
  "interfaces": [],
  "mixins": [],
  "functionName": null,
  "clazz": {
    "location": {
      "start": {
        "line": 23,
        "column": 0,
        "index": 601
      },
      "end": {
        "line": 88,
        "column": 3,
        "index": 2002
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": "<p>This exception is thrown by the {@link qx.event.GlobalError} handler if a\n observed method throws an exception.</p>"
        }
      ]
    }
  },
  "type": "class",
  "construct": {
    "location": {
      "start": {
        "line": 30,
        "column": 2,
        "index": 754
      },
      "end": {
        "line": 54,
        "column": 3,
        "index": 1451
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": ""
        }
      ],
      "@param": [
        {
          "name": "@param",
          "body": "exc {Error} source exception",
          "paramName": "exc",
          "description": " source exception",
          "type": "Error"
        },
        {
          "name": "@param",
          "body": "args {Array} arguments",
          "paramName": "args",
          "description": " arguments",
          "type": "Array"
        }
      ]
    }
  },
  "members": {
    "__exc": {
      "location": {
        "start": {
          "line": 57,
          "column": 4,
          "index": 1471
        },
        "end": {
          "line": 57,
          "column": 15,
          "index": 1482
        }
      },
      "type": "variable",
      "access": "private"
    },
    "__arguments": {
      "location": {
        "start": {
          "line": 58,
          "column": 4,
          "index": 1488
        },
        "end": {
          "line": 58,
          "column": 21,
          "index": 1505
        }
      },
      "type": "variable",
      "access": "private"
    },
    "__failMessage": {
      "location": {
        "start": {
          "line": 59,
          "column": 4,
          "index": 1511
        },
        "end": {
          "line": 59,
          "column": 23,
          "index": 1530
        }
      },
      "type": "variable",
      "access": "private"
    },
    "getArguments": {
      "location": {
        "start": {
          "line": 75,
          "column": 4,
          "index": 1786
        },
        "end": {
          "line": 77,
          "column": 5,
          "index": 1839
        }
      },
      "jsdoc": {
        "@description": [
          {
            "name": "@description",
            "body": "<p>Returns the arguments which are</p>"
          }
        ],
        "@return": [
          {
            "name": "@return",
            "body": "{Object} arguments",
            "type": "qx.core.Object",
            "description": " arguments"
          }
        ]
      },
      "type": "function",
      "access": "public"
    },
    "getSourceException": {
      "location": {
        "start": {
          "line": 84,
          "column": 4,
          "index": 1941
        },
        "end": {
          "line": 86,
          "column": 5,
          "index": 1994
        }
      },
      "jsdoc": {
        "@description": [
          {
            "name": "@description",
            "body": "<p>Get the source exception</p>"
          }
        ],
        "@return": [
          {
            "name": "@return",
            "body": "{Error} source exception",
            "type": "Error",
            "description": " source exception"
          }
        ]
      },
      "type": "function",
      "access": "public"
    }
  },
  "descendants": []
}